server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        group: springcloud
        server-addr: localhost:8848
    loadbalancer:
      cache:
        enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice   #路由目标地址
          predicates:
#            - Path=/user/**   #路径断言，判断路径是否是以/user开头
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#      default-filters:  #对所有的路由都生效
#        - AddRequestHeader=X-Request-red, blue
#          filters:
#            - AddRequestHeader=X-Request-red, blue
