spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456ly
  jpa:
    show-sql: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456ly
    ssl: false
    timeout: 1000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #namespace: acbb9b19-8d79-4362-84ab-318b18bbf982
        group: springcloud
    #负载均衡
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
  zipkin:
    enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


rocketmq:
  name-server: localhost:9876
  producer:
    group: orderservice
    retry-times-when-send-failed: 2

mybatis-plus:
  # type-aliases-package: com.ly.**.entity
  mapper-locations: classpath:/mapper/*.xml   #Mapper XML文件的位置，多个文件用逗号分隔。
  global-config:  #全局配置
    banner: false
    db-config:  #数据库配置
      id-type: auto   #主键类型，可选值为auto、input、assign、id_worker、uuid、none
      table-prefix: ly_   #表前缀，生成的SQL语句中表名会添加该前缀
  configuration:  #MyBatis的配置
    map-underscore-to-camel-case: true  #是否开启下划线转驼峰命名，可选值为true和false
    auto-mapping-unknown-column-behavior: WARNING
    jdbc-type-for-null: VARCHAR
    # 配置Mybatis的日志输出级别
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启缓存
    cache-enabled: true
    # 缓存默认使用的缓存实现类
    local-cache-scope: session
    # 设置flushCache="true"时，是否刷新缓存
    local-cache-eviction: LRU
    # 设置缓存大小，0表示无限制
    local-cache-size: 1024
    # 开启缓存统计工具
    local-cache-statistics: true
    # 指定自定义缓存实现类
    # local-cache-implementation: com.example.MyCache

swagger:
  enabled: true
  version: "@project.version@"
  #    title: ${spring.application.name}
  #    description: 信贷模块
  #    base-package: com.dhcc.cms.c5
  docket:
    bflw:
      title: ${spring.application.name}
      description: 产品模块
      base-package: com.ly.**.controller

knife4j:
  title: 产品模块
  description: 产品模块接口描述
  version: 1.0
  base-package: com.ly.**.controller
  enable: true

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
logging:
  level:
    com.dhcc.cms: debug
    com.alibaba.nacos.client.naming: error

